// european-large-caps-list.ts
// European large-cap constituents (expanded from FTSEurofirst 100, as of March 2026).
// Covers: Netherlands, Germany, France, UK, Spain, Italy, Switzerland, Denmark,
//         Sweden, Finland, Belgium, Austria, Ireland.
//
// symbol        = Finnhub/Yahoo Finance ticker — used as the DB primary key (globally unique)
//                 e.g. "ASML.AS", "AZN.L", "SAP.XETRA", "NESN.SW"
// stooq_ticker  = Stooq price-feed ticker (not used by sync — Yahoo Finance is used instead)
// index_weight  = approximate decimal fraction based on market cap (not a live index weight)
//
// VERIFY note: tickers marked // VERIFY may need confirming against a live data source.

import type { GicsSector } from "@/lib/sp500/types";

export type Constituent = {
  symbol: string;
  name: string;
  country: string;
  sector: GicsSector;
  stooq_ticker: string;
  finnhub_ticker: string;
  index_weight: number;
};

export const EUROPEAN_LARGE_CAPS: Constituent[] = [
  // ── NETHERLANDS (21) ────────────────────────────────────────────────────────
  { symbol: "ASML.AS",  name: "ASML Holding NV",             country: "Netherlands", sector: "Information Technology", stooq_ticker: "asml.nl",  finnhub_ticker: "ASML.AS",  index_weight: 0.0539 },
  { symbol: "INGA.AS",  name: "ING Groep NV",                country: "Netherlands", sector: "Financials",             stooq_ticker: "inga.nl",  finnhub_ticker: "INGA.AS",  index_weight: 0.0085 },
  { symbol: "ADYEN.AS", name: "Adyen NV",                    country: "Netherlands", sector: "Information Technology", stooq_ticker: "adyen.nl", finnhub_ticker: "ADYEN.AS", index_weight: 0.0075 },
  { symbol: "HEIA.AS",  name: "Heineken NV",                 country: "Netherlands", sector: "Consumer Staples",       stooq_ticker: "heia.nl",  finnhub_ticker: "HEIA.AS",  index_weight: 0.0070 },
  { symbol: "WKL.AS",   name: "Wolters Kluwer NV",           country: "Netherlands", sector: "Information Technology", stooq_ticker: "wkl.nl",   finnhub_ticker: "WKL.AS",   index_weight: 0.0055 },
  { symbol: "DSFIR.AS", name: "dsm-firmenich AG",            country: "Netherlands", sector: "Materials",              stooq_ticker: "dsfir.nl", finnhub_ticker: "DSFIR.AS", index_weight: 0.0050 },
  { symbol: "NN.AS",    name: "NN Group NV",                 country: "Netherlands", sector: "Financials",             stooq_ticker: "nn.nl",    finnhub_ticker: "NN.AS",    index_weight: 0.0040 },
  { symbol: "AGN.AS",   name: "Aegon NV",                    country: "Netherlands", sector: "Financials",             stooq_ticker: "agn.nl",   finnhub_ticker: "AGN.AS",   index_weight: 0.0030 },
  { symbol: "RAND.AS",  name: "Randstad NV",                 country: "Netherlands", sector: "Industrials",            stooq_ticker: "rand.nl",  finnhub_ticker: "RAND.AS",  index_weight: 0.0030 },
  { symbol: "PRX.AS",  name: "Prosus NV",                   country: "Netherlands", sector: "Communication Services", stooq_ticker: "prx.nl",   finnhub_ticker: "PRX.AS",   index_weight: 0.0060 },
  { symbol: "AD.AS",   name: "Ahold Delhaize NV",           country: "Netherlands", sector: "Consumer Staples",       stooq_ticker: "ad.nl",    finnhub_ticker: "AD.AS",    index_weight: 0.0055 },
  { symbol: "ASM.AS",  name: "ASM International NV",        country: "Netherlands", sector: "Information Technology", stooq_ticker: "asm.nl",   finnhub_ticker: "ASM.AS",   index_weight: 0.0050 },
  { symbol: "UMG.AS",  name: "Universal Music Group NV",    country: "Netherlands", sector: "Communication Services", stooq_ticker: "umg.nl",   finnhub_ticker: "UMG.AS",   index_weight: 0.0045 },
  { symbol: "ABN.AS",  name: "ABN AMRO Bank NV",            country: "Netherlands", sector: "Financials",             stooq_ticker: "abn.nl",   finnhub_ticker: "ABN.AS",   index_weight: 0.0030 },
  { symbol: "KPN.AS",  name: "Koninklijke KPN NV",          country: "Netherlands", sector: "Communication Services", stooq_ticker: "kpn.nl",   finnhub_ticker: "KPN.AS",   index_weight: 0.0025 },
  { symbol: "EXO.AS",  name: "Exor NV",                     country: "Netherlands", sector: "Financials",             stooq_ticker: "exo.nl",   finnhub_ticker: "EXO.AS",   index_weight: 0.0040 },
  { symbol: "MT.AS",   name: "ArcelorMittal SA",            country: "Netherlands", sector: "Materials",              stooq_ticker: "mt.nl",    finnhub_ticker: "MT.AS",    index_weight: 0.0035 },
  { symbol: "PHIA.AS", name: "Koninklijke Philips NV",      country: "Netherlands", sector: "Health Care",            stooq_ticker: "phia.nl",  finnhub_ticker: "PHIA.AS",  index_weight: 0.0022 },
  { symbol: "BESI.AS", name: "BE Semiconductor Industries NV", country: "Netherlands", sector: "Information Technology", stooq_ticker: "besi.nl", finnhub_ticker: "BESI.AS",  index_weight: 0.0014 },
  { symbol: "JDEP.AS", name: "JDE Peet's NV",               country: "Netherlands", sector: "Consumer Staples",       stooq_ticker: "jdep.nl",  finnhub_ticker: "JDEP.AS",  index_weight: 0.0013 },
  { symbol: "ENX.PA",   name: "Euronext NV",                 country: "Netherlands", sector: "Financials",             stooq_ticker: "enx.nl",    finnhub_ticker: "ENX.PA",   index_weight: 0.0013 },
  { symbol: "ASRNL.AS", name: "ASR Nederland NV",            country: "Netherlands", sector: "Financials",             stooq_ticker: "asrnl.nl",  finnhub_ticker: "ASRNL.AS", index_weight: 0.0011 },
  { symbol: "AKZA.AS",  name: "Akzo Nobel NV",               country: "Netherlands", sector: "Materials",              stooq_ticker: "akza.nl",   finnhub_ticker: "AKZA.AS",  index_weight: 0.0008 },

  // ── GERMANY (46) ────────────────────────────────────────────────────────────
  { symbol: "SAP.XETRA",   name: "SAP SE",                         country: "Germany", sector: "Information Technology", stooq_ticker: "sap.de",   finnhub_ticker: "SAP.XETRA",   index_weight: 0.0318 },
  { symbol: "SIE.XETRA",   name: "Siemens AG",                     country: "Germany", sector: "Industrials",            stooq_ticker: "sie.de",   finnhub_ticker: "SIE.XETRA",   index_weight: 0.0261 },
  { symbol: "ALV.XETRA",   name: "Allianz SE",                     country: "Germany", sector: "Financials",             stooq_ticker: "alv.de",   finnhub_ticker: "ALV.XETRA",   index_weight: 0.0224 },
  { symbol: "DTE.XETRA",   name: "Deutsche Telekom AG",            country: "Germany", sector: "Communication Services", stooq_ticker: "dte.de",   finnhub_ticker: "DTE.XETRA",   index_weight: 0.0180 },
  { symbol: "MUV2.XETRA",  name: "Munich Re",                      country: "Germany", sector: "Financials",             stooq_ticker: "muv2.de",  finnhub_ticker: "MUV2.XETRA",  index_weight: 0.0150 },
  { symbol: "BMW.XETRA",   name: "BMW AG",                         country: "Germany", sector: "Consumer Discretionary", stooq_ticker: "bmw.de",   finnhub_ticker: "BMW.XETRA",   index_weight: 0.0090 },
  { symbol: "BAS.XETRA",   name: "BASF SE",                        country: "Germany", sector: "Materials",              stooq_ticker: "bas.de",   finnhub_ticker: "BAS.XETRA",   index_weight: 0.0080 },
  { symbol: "ENR.XETRA",   name: "Siemens Energy AG",              country: "Germany", sector: "Industrials",            stooq_ticker: "enr.de",   finnhub_ticker: "ENR.XETRA",   index_weight: 0.0080 },
  { symbol: "IFX.XETRA",   name: "Infineon Technologies AG",       country: "Germany", sector: "Information Technology", stooq_ticker: "ifx.de",   finnhub_ticker: "IFX.XETRA",   index_weight: 0.0080 },
  { symbol: "MBG.XETRA",   name: "Mercedes-Benz Group AG",         country: "Germany", sector: "Consumer Discretionary", stooq_ticker: "mbg.de",   finnhub_ticker: "MBG.XETRA",   index_weight: 0.0075 },
  { symbol: "DHL.XETRA",   name: "DHL Group",                      country: "Germany", sector: "Industrials",            stooq_ticker: "dhl.de",   finnhub_ticker: "DHL.XETRA",   index_weight: 0.0075 },
  { symbol: "DBK.XETRA",   name: "Deutsche Bank AG",               country: "Germany", sector: "Financials",             stooq_ticker: "dbk.de",   finnhub_ticker: "DBK.XETRA",   index_weight: 0.0070 },
  { symbol: "DB1.XETRA",   name: "Deutsche Börse AG",              country: "Germany", sector: "Financials",             stooq_ticker: "db1.de",   finnhub_ticker: "DB1.XETRA",   index_weight: 0.0070 },
  { symbol: "VOW3.XETRA",  name: "Volkswagen AG",                  country: "Germany", sector: "Consumer Discretionary", stooq_ticker: "vow3.de",  finnhub_ticker: "VOW3.XETRA",  index_weight: 0.0070 },
  { symbol: "ADS.XETRA",   name: "Adidas AG",                      country: "Germany", sector: "Consumer Discretionary", stooq_ticker: "ads.de",   finnhub_ticker: "ADS.XETRA",   index_weight: 0.0070 },
  { symbol: "BAYN.XETRA",  name: "Bayer AG",                       country: "Germany", sector: "Health Care",            stooq_ticker: "bayn.de",  finnhub_ticker: "BAYN.XETRA",  index_weight: 0.0060 },
  { symbol: "EOAN.XETRA",  name: "E.ON SE",                        country: "Germany", sector: "Utilities",              stooq_ticker: "eoan.de",  finnhub_ticker: "EOAN.XETRA",  index_weight: 0.0060 },
  { symbol: "RWE.XETRA",   name: "RWE AG",                         country: "Germany", sector: "Utilities",              stooq_ticker: "rwe.de",   finnhub_ticker: "RWE.XETRA",   index_weight: 0.0055 },
  { symbol: "RHM.XETRA",   name: "Rheinmetall AG",                 country: "Germany", sector: "Industrials",            stooq_ticker: "rhm.de",   finnhub_ticker: "RHM.XETRA",   index_weight: 0.0055 },
  { symbol: "PAH3.XETRA",  name: "Porsche Automobil Holding SE",   country: "Germany", sector: "Consumer Discretionary", stooq_ticker: "pah3.de",  finnhub_ticker: "PAH3.XETRA",  index_weight: 0.0045 },
  { symbol: "HEN3.XETRA",  name: "Henkel AG & Co KGaA",            country: "Germany", sector: "Consumer Staples",       stooq_ticker: "hen3.de",  finnhub_ticker: "HEN3.XETRA",  index_weight: 0.0035 },
  { symbol: "MRK.XETRA",   name: "Merck KGaA",                     country: "Germany", sector: "Health Care",            stooq_ticker: "mrk.de",   finnhub_ticker: "MRK.XETRA",   index_weight: 0.0070 },
  { symbol: "SHL.XETRA",   name: "Siemens Healthineers AG",         country: "Germany", sector: "Health Care",            stooq_ticker: "shl.de",   finnhub_ticker: "SHL.XETRA",   index_weight: 0.0060 },
  { symbol: "P911.XETRA",  name: "Dr. Ing. h.c. F. Porsche AG",    country: "Germany", sector: "Consumer Discretionary", stooq_ticker: "p911.de",  finnhub_ticker: "P911.XETRA",  index_weight: 0.0055 },
  { symbol: "DTG.XETRA",   name: "Daimler Truck Holding AG",        country: "Germany", sector: "Industrials",            stooq_ticker: "dtg.de",   finnhub_ticker: "DTG.XETRA",   index_weight: 0.0040 },
  { symbol: "CBK.XETRA",   name: "Commerzbank AG",                  country: "Germany", sector: "Financials",             stooq_ticker: "cbk.de",   finnhub_ticker: "CBK.XETRA",   index_weight: 0.0030 },
  { symbol: "HEI.XETRA",   name: "Heidelberg Materials AG",         country: "Germany", sector: "Materials",              stooq_ticker: "hei.de",   finnhub_ticker: "HEI.XETRA",   index_weight: 0.0030 },
  { symbol: "HNR1.XETRA",  name: "Hannover Rück SE",                country: "Germany", sector: "Financials",             stooq_ticker: "hnr1.de",  finnhub_ticker: "HNR1.XETRA",  index_weight: 0.0045 },
  { symbol: "VNA.XETRA",   name: "Vonovia SE",                      country: "Germany", sector: "Real Estate",            stooq_ticker: "vna.de",   finnhub_ticker: "VNA.XETRA",   index_weight: 0.0035 },
  { symbol: "MTX.XETRA",   name: "MTU Aero Engines AG",             country: "Germany", sector: "Industrials",            stooq_ticker: "mtx.de",   finnhub_ticker: "MTX.XETRA",   index_weight: 0.0030 },
  { symbol: "BEI.XETRA",   name: "Beiersdorf AG",                   country: "Germany", sector: "Consumer Staples",       stooq_ticker: "bei.de",   finnhub_ticker: "BEI.XETRA",   index_weight: 0.0035 },
  { symbol: "CON.XETRA",   name: "Continental AG",                  country: "Germany", sector: "Consumer Discretionary", stooq_ticker: "con.de",   finnhub_ticker: "CON.XETRA",   index_weight: 0.0025 },
  { symbol: "SY1.XETRA",   name: "Symrise AG",                      country: "Germany", sector: "Materials",              stooq_ticker: "sy1.de",   finnhub_ticker: "SY1.XETRA",   index_weight: 0.0020 },
  { symbol: "BNR.XETRA",   name: "Brenntag SE",                     country: "Germany", sector: "Materials",              stooq_ticker: "bnr.de",   finnhub_ticker: "BNR.XETRA",   index_weight: 0.0020 },
  { symbol: "ZAL.XETRA",   name: "Zalando SE",                      country: "Germany", sector: "Consumer Discretionary", stooq_ticker: "zal.de",   finnhub_ticker: "ZAL.XETRA",   index_weight: 0.0018 },
  { symbol: "HOT.XETRA",   name: "Hochtief AG",                     country: "Germany", sector: "Industrials",            stooq_ticker: "hot.de",   finnhub_ticker: "HOT.XETRA",   index_weight: 0.0026 },
  { symbol: "FRE.XETRA",   name: "Fresenius SE & Co KGaA",          country: "Germany", sector: "Health Care",            stooq_ticker: "fre.de",   finnhub_ticker: "FRE.XETRA",   index_weight: 0.0023 },
  { symbol: "TLX.XETRA",   name: "Talanx AG",                       country: "Germany", sector: "Financials",             stooq_ticker: "tlx.de",   finnhub_ticker: "TLX.XETRA",   index_weight: 0.0023 },
  { symbol: "HLAG.XETRA",  name: "Hapag-Lloyd AG",                  country: "Germany", sector: "Industrials",            stooq_ticker: "hlag.de",  finnhub_ticker: "HLAG.XETRA",  index_weight: 0.0021 },
  { symbol: "KBX.XETRA",   name: "Knorr-Bremse AG",                 country: "Germany", sector: "Industrials",            stooq_ticker: "kbx.de",   finnhub_ticker: "KBX.XETRA",   index_weight: 0.0015 },
  { symbol: "8TRA.XETRA",  name: "Traton SE",                       country: "Germany", sector: "Consumer Discretionary", stooq_ticker: "8tra.de",  finnhub_ticker: "8TRA.XETRA",  index_weight: 0.0014 },
  { symbol: "UN0.XETRA",   name: "Uniper SE",                       country: "Germany", sector: "Utilities",              stooq_ticker: "un0.de",   finnhub_ticker: "UN0.XETRA",   index_weight: 0.0012 },
  { symbol: "SRT.XETRA",   name: "Sartorius AG",                    country: "Germany", sector: "Health Care",            stooq_ticker: "srt.de",   finnhub_ticker: "SRT.XETRA",   index_weight: 0.0011 },

  { symbol: "DWS.XETRA",   name: "DWS Group GmbH & Co KGaA",        country: "Germany", sector: "Financials",             stooq_ticker: "dws.de",   finnhub_ticker: "DWS.XETRA",   index_weight: 0.0010 },
  { symbol: "FME.XETRA",   name: "Fresenius Medical Care AG",        country: "Germany", sector: "Health Care",            stooq_ticker: "fme.de",   finnhub_ticker: "FME.XETRA",   index_weight: 0.0010 },
  { symbol: "NDX1.XETRA",  name: "Nordex SE",                        country: "Germany", sector: "Industrials",            stooq_ticker: "ndx1.de",  finnhub_ticker: "NDX1.XETRA",  index_weight: 0.0009 },

  // ── FRANCE (47) ─────────────────────────────────────────────────────────────
  { symbol: "MC.PA",   name: "LVMH Moët Hennessy Louis Vuitton SE",  country: "France", sector: "Consumer Discretionary", stooq_ticker: "mc.fr",   finnhub_ticker: "MC.PA",   index_weight: 0.0245 },
  { symbol: "AIR.PA",  name: "Airbus SE",                             country: "France", sector: "Industrials",            stooq_ticker: "air.fr",  finnhub_ticker: "AIR.PA",  index_weight: 0.0220 },
  { symbol: "SU.PA",   name: "Schneider Electric SE",                 country: "France", sector: "Industrials",            stooq_ticker: "su.fr",   finnhub_ticker: "SU.PA",   index_weight: 0.0189 },
  { symbol: "TTE.PA",  name: "TotalEnergies SE",                      country: "France", sector: "Energy",                 stooq_ticker: "tte.fr",  finnhub_ticker: "TTE.PA",  index_weight: 0.0170 },
  { symbol: "RMS.PA",  name: "Hermès International SCA",              country: "France", sector: "Consumer Discretionary", stooq_ticker: "rms.fr",  finnhub_ticker: "RMS.PA",  index_weight: 0.0160 },
  { symbol: "SAN.PA",  name: "Sanofi SA",                             country: "France", sector: "Health Care",            stooq_ticker: "san.fr",  finnhub_ticker: "SAN.PA",  index_weight: 0.0140 },
  { symbol: "OR.PA",   name: "L'Oréal SA",                            country: "France", sector: "Consumer Staples",       stooq_ticker: "or.fr",   finnhub_ticker: "OR.PA",   index_weight: 0.0120 },
  { symbol: "BNP.PA",  name: "BNP Paribas SA",                        country: "France", sector: "Financials",             stooq_ticker: "bnp.fr",  finnhub_ticker: "BNP.PA",  index_weight: 0.0110 },
  { symbol: "CS.PA",   name: "AXA SA",                                country: "France", sector: "Financials",             stooq_ticker: "cs.fr",   finnhub_ticker: "CS.PA",   index_weight: 0.0102 }, // VERIFY: AXA trades as "CS" on Euronext Paris
  { symbol: "AI.PA",   name: "Air Liquide SA",                        country: "France", sector: "Materials",              stooq_ticker: "ai.fr",   finnhub_ticker: "AI.PA",   index_weight: 0.0090 },
  { symbol: "SAF.PA",  name: "Safran SA",                             country: "France", sector: "Industrials",            stooq_ticker: "saf.fr",  finnhub_ticker: "SAF.PA",  index_weight: 0.0080 },
  { symbol: "DG.PA",   name: "Vinci SA",                              country: "France", sector: "Industrials",            stooq_ticker: "dg.fr",   finnhub_ticker: "DG.PA",   index_weight: 0.0070 },
  { symbol: "GLE.PA",  name: "Société Générale SA",                   country: "France", sector: "Financials",             stooq_ticker: "gle.fr",  finnhub_ticker: "GLE.PA",  index_weight: 0.0065 },
  { symbol: "BN.PA",   name: "Danone SA",                             country: "France", sector: "Consumer Staples",       stooq_ticker: "bn.fr",   finnhub_ticker: "BN.PA",   index_weight: 0.0060 },
  { symbol: "ENGI.PA", name: "Engie SA",                              country: "France", sector: "Utilities",              stooq_ticker: "engi.fr", finnhub_ticker: "ENGI.PA", index_weight: 0.0060 },
  { symbol: "KER.PA",  name: "Kering SA",                             country: "France", sector: "Consumer Discretionary", stooq_ticker: "ker.fr",  finnhub_ticker: "KER.PA",  index_weight: 0.0060 },
  { symbol: "SGO.PA",  name: "Compagnie de Saint-Gobain SA",          country: "France", sector: "Industrials",            stooq_ticker: "sgo.fr",  finnhub_ticker: "SGO.PA",  index_weight: 0.0055 },
  { symbol: "RI.PA",   name: "Pernod Ricard SA",                      country: "France", sector: "Consumer Staples",       stooq_ticker: "ri.fr",   finnhub_ticker: "RI.PA",   index_weight: 0.0055 },
  { symbol: "PUB.PA",  name: "Publicis Groupe SA",                    country: "France", sector: "Communication Services", stooq_ticker: "pub.fr",  finnhub_ticker: "PUB.PA",  index_weight: 0.0050 },
  { symbol: "EL.PA",   name: "EssilorLuxottica SA",                   country: "France", sector: "Health Care",            stooq_ticker: "el.fr",   finnhub_ticker: "EL.PA",   index_weight: 0.0090 },
  { symbol: "CDI.PA",  name: "Christian Dior SE",                     country: "France", sector: "Consumer Discretionary", stooq_ticker: "cdi.fr",  finnhub_ticker: "CDI.PA",  index_weight: 0.0080 },
  { symbol: "ACA.PA",  name: "Crédit Agricole SA",                    country: "France", sector: "Financials",             stooq_ticker: "aca.fr",  finnhub_ticker: "ACA.PA",  index_weight: 0.0060 },
  { symbol: "HO.PA",   name: "Thales SA",                             country: "France", sector: "Industrials",            stooq_ticker: "ho.fr",   finnhub_ticker: "HO.PA",   index_weight: 0.0050 },
  { symbol: "ORA.PA",  name: "Orange SA",                             country: "France", sector: "Communication Services", stooq_ticker: "ora.fr",  finnhub_ticker: "ORA.PA",  index_weight: 0.0040 },
  { symbol: "LR.PA",   name: "Legrand SA",                            country: "France", sector: "Industrials",            stooq_ticker: "lr.fr",   finnhub_ticker: "LR.PA",   index_weight: 0.0040 },
  { symbol: "DSY.PA",  name: "Dassault Systèmes SE",                  country: "France", sector: "Information Technology", stooq_ticker: "dsy.fr",  finnhub_ticker: "DSY.PA",  index_weight: 0.0060 },
  { symbol: "CAP.PA",  name: "Capgemini SE",                           country: "France", sector: "Information Technology", stooq_ticker: "cap.fr",  finnhub_ticker: "CAP.PA",  index_weight: 0.0055 },
  { symbol: "ML.PA",   name: "Compagnie Générale des Établissements Michelin", country: "France", sector: "Consumer Discretionary", stooq_ticker: "ml.fr", finnhub_ticker: "ML.PA", index_weight: 0.0050 },
  { symbol: "STMPA.PA", name: "STMicroelectronics NV",                 country: "France", sector: "Information Technology", stooq_ticker: "stm.fr",  finnhub_ticker: "STMPA.PA", index_weight: 0.0045 },
  { symbol: "VIE.PA",  name: "Veolia Environnement SA",                country: "France", sector: "Utilities",              stooq_ticker: "vie.fr",  finnhub_ticker: "VIE.PA",  index_weight: 0.0040 },
  { symbol: "RNO.PA",  name: "Renault SA",                             country: "France", sector: "Consumer Discretionary", stooq_ticker: "rno.fr",  finnhub_ticker: "RNO.PA",  index_weight: 0.0035 },
  { symbol: "CA.PA",   name: "Carrefour SA",                           country: "France", sector: "Consumer Staples",       stooq_ticker: "ca.fr",   finnhub_ticker: "CA.PA",   index_weight: 0.0035 },
  { symbol: "EN.PA",   name: "Bouygues SA",                            country: "France", sector: "Industrials",            stooq_ticker: "en.fr",   finnhub_ticker: "EN.PA",   index_weight: 0.0030 },
  { symbol: "AC.PA",   name: "Accor SA",                               country: "France", sector: "Consumer Discretionary", stooq_ticker: "ac.fr",   finnhub_ticker: "AC.PA",   index_weight: 0.0030 },
  { symbol: "URW.PA",  name: "Unibail-Rodamco-Westfield SE",           country: "France", sector: "Real Estate",            stooq_ticker: "urw.fr",  finnhub_ticker: "URW.PA",  index_weight: 0.0028 },
  { symbol: "ERF.PA",  name: "Eurofins Scientific SE",                 country: "France", sector: "Health Care",            stooq_ticker: "erf.fr",  finnhub_ticker: "ERF.PA",  index_weight: 0.0028 },
  { symbol: "TEP.PA",  name: "Teleperformance SE",                     country: "France", sector: "Industrials",            stooq_ticker: "tep.fr",  finnhub_ticker: "TEP.PA",  index_weight: 0.0025 },
  { symbol: "EDEN.PA", name: "Edenred SE",                             country: "France", sector: "Industrials",            stooq_ticker: "eden.fr", finnhub_ticker: "EDEN.PA", index_weight: 0.0025 },
  { symbol: "VIV.PA",  name: "Vivendi SE",                             country: "France", sector: "Communication Services", stooq_ticker: "viv.fr",  finnhub_ticker: "VIV.PA",  index_weight: 0.0020 },
  { symbol: "AM.PA",   name: "Dassault Aviation SA",                   country: "France", sector: "Industrials",            stooq_ticker: "am.fr",   finnhub_ticker: "AM.PA",   index_weight: 0.0023 },
  { symbol: "AMUN.PA", name: "Amundi SA",                              country: "France", sector: "Financials",             stooq_ticker: "amun.fr", finnhub_ticker: "AMUN.PA", index_weight: 0.0014 },
  { symbol: "FGR.PA",  name: "Eiffage SA",                            country: "France", sector: "Industrials",            stooq_ticker: "fgr.fr",  finnhub_ticker: "FGR.PA",  index_weight: 0.0012 },
  { symbol: "BOL.PA",  name: "Bolloré SE",                            country: "France", sector: "Industrials",            stooq_ticker: "bol.fr",  finnhub_ticker: "BOL.PA",  index_weight: 0.0012 },
  { symbol: "BVI.PA",  name: "Bureau Veritas SA",                     country: "France", sector: "Industrials",            stooq_ticker: "bvi.fr",  finnhub_ticker: "BVI.PA",  index_weight: 0.0011 },
  { symbol: "ALO.PA",  name: "Alstom SA",                             country: "France", sector: "Industrials",            stooq_ticker: "alo.fr",  finnhub_ticker: "ALO.PA",  index_weight: 0.0011 },
  { symbol: "BIM.PA",  name: "bioMérieux SA",                         country: "France", sector: "Health Care",            stooq_ticker: "bim.fr",  finnhub_ticker: "BIM.PA",  index_weight: 0.0010 },
  { symbol: "ADP.PA",  name: "Aéroports de Paris SA",                 country: "France", sector: "Industrials",            stooq_ticker: "adp.fr",  finnhub_ticker: "ADP.PA",  index_weight: 0.0010 },

  // ── UNITED KINGDOM (70) ─────────────────────────────────────────────────────
  { symbol: "AZN.L",  name: "AstraZeneca plc",               country: "United Kingdom", sector: "Health Care",            stooq_ticker: "azn.uk",  finnhub_ticker: "AZN.L",  index_weight: 0.0352 },
  { symbol: "HSBA.L", name: "HSBC Holdings plc",             country: "United Kingdom", sector: "Financials",             stooq_ticker: "hsba.uk", finnhub_ticker: "HSBA.L", index_weight: 0.0343 },
  { symbol: "SHEL.L", name: "Shell plc",                     country: "United Kingdom", sector: "Energy",                 stooq_ticker: "shel.uk", finnhub_ticker: "SHEL.L", index_weight: 0.0270 },
  { symbol: "ULVR.L", name: "Unilever plc",                  country: "United Kingdom", sector: "Consumer Staples",       stooq_ticker: "ulvr.uk", finnhub_ticker: "ULVR.L", index_weight: 0.0150 },
  { symbol: "BP.L",   name: "BP plc",                        country: "United Kingdom", sector: "Energy",                 stooq_ticker: "bp.uk",   finnhub_ticker: "BP.L",   index_weight: 0.0130 },
  { symbol: "RR.L",   name: "Rolls-Royce Holdings plc",      country: "United Kingdom", sector: "Industrials",            stooq_ticker: "rr.uk",   finnhub_ticker: "RR.L",   index_weight: 0.0115 },
  { symbol: "GSK.L",  name: "GSK plc",                       country: "United Kingdom", sector: "Health Care",            stooq_ticker: "gsk.uk",  finnhub_ticker: "GSK.L",  index_weight: 0.0120 },
  { symbol: "RIO.L",  name: "Rio Tinto plc",                 country: "United Kingdom", sector: "Materials",              stooq_ticker: "rio.uk",  finnhub_ticker: "RIO.L",  index_weight: 0.0100 },
  { symbol: "BA.L",   name: "BAE Systems plc",               country: "United Kingdom", sector: "Industrials",            stooq_ticker: "ba.uk",   finnhub_ticker: "BA.L",   index_weight: 0.0095 },
  { symbol: "DGE.L",  name: "Diageo plc",                    country: "United Kingdom", sector: "Consumer Staples",       stooq_ticker: "dge.uk",  finnhub_ticker: "DGE.L",  index_weight: 0.0095 },
  { symbol: "BARC.L", name: "Barclays plc",                  country: "United Kingdom", sector: "Financials",             stooq_ticker: "barc.uk", finnhub_ticker: "BARC.L", index_weight: 0.0090 },
  { symbol: "BHP.L",  name: "BHP Group Limited",             country: "United Kingdom", sector: "Materials",              stooq_ticker: "bhp.uk",  finnhub_ticker: "BHP.L",  index_weight: 0.0090 },
  { symbol: "GLEN.L", name: "Glencore plc",                  country: "United Kingdom", sector: "Materials",              stooq_ticker: "glen.uk", finnhub_ticker: "GLEN.L", index_weight: 0.0080 },
  { symbol: "III.L",  name: "3i Group plc",                  country: "United Kingdom", sector: "Financials",             stooq_ticker: "iii.uk",  finnhub_ticker: "III.L",  index_weight: 0.0075 },
  { symbol: "CPG.L",  name: "Compass Group plc",             country: "United Kingdom", sector: "Consumer Discretionary", stooq_ticker: "cpg.uk",  finnhub_ticker: "CPG.L",  index_weight: 0.0070 },
  { symbol: "LLOY.L", name: "Lloyds Banking Group plc",      country: "United Kingdom", sector: "Financials",             stooq_ticker: "lloy.uk", finnhub_ticker: "LLOY.L", index_weight: 0.0070 },
  { symbol: "NG.L",   name: "National Grid plc",             country: "United Kingdom", sector: "Utilities",              stooq_ticker: "ng.uk",   finnhub_ticker: "NG.L",   index_weight: 0.0065 },
  { symbol: "FERG.L", name: "Ferguson plc",                  country: "United Kingdom", sector: "Industrials",            stooq_ticker: "ferg.uk", finnhub_ticker: "FERG.L", index_weight: 0.0065 },
  { symbol: "EXPN.L", name: "Experian plc",                  country: "United Kingdom", sector: "Industrials",            stooq_ticker: "expn.uk", finnhub_ticker: "EXPN.L", index_weight: 0.0065 },
  { symbol: "REL.L",  name: "RELX plc",                      country: "United Kingdom", sector: "Industrials",            stooq_ticker: "rel.uk",  finnhub_ticker: "REL.L",  index_weight: 0.0065 },
  { symbol: "HLN.L",  name: "Haleon plc",                    country: "United Kingdom", sector: "Consumer Staples",       stooq_ticker: "hln.uk",  finnhub_ticker: "HLN.L",  index_weight: 0.0060 },
  { symbol: "AHT.L",  name: "Ashtead Group plc",             country: "United Kingdom", sector: "Industrials",            stooq_ticker: "aht.uk",  finnhub_ticker: "AHT.L",  index_weight: 0.0060 },
  { symbol: "STAN.L", name: "Standard Chartered plc",        country: "United Kingdom", sector: "Financials",             stooq_ticker: "stan.uk", finnhub_ticker: "STAN.L", index_weight: 0.0060 },
  { symbol: "IHG.L",  name: "InterContinental Hotels Group", country: "United Kingdom", sector: "Consumer Discretionary", stooq_ticker: "ihg.uk",  finnhub_ticker: "IHG.L",  index_weight: 0.0055 },
  { symbol: "NWG.L",  name: "NatWest Group plc",             country: "United Kingdom", sector: "Financials",             stooq_ticker: "nwg.uk",  finnhub_ticker: "NWG.L",  index_weight: 0.0055 },
  { symbol: "PRU.L",  name: "Prudential plc",                country: "United Kingdom", sector: "Financials",             stooq_ticker: "pru.uk",  finnhub_ticker: "PRU.L",  index_weight: 0.0055 },
  { symbol: "RKT.L",  name: "Reckitt Benckiser Group plc",   country: "United Kingdom", sector: "Consumer Staples",       stooq_ticker: "rkt.uk",  finnhub_ticker: "RKT.L",  index_weight: 0.0055 },
  { symbol: "AAL.L",  name: "Anglo American plc",            country: "United Kingdom", sector: "Materials",              stooq_ticker: "aal.uk",  finnhub_ticker: "AAL.L",  index_weight: 0.0055 },
  { symbol: "MRO.L",  name: "Melrose Industries plc",        country: "United Kingdom", sector: "Industrials",            stooq_ticker: "mro.uk",  finnhub_ticker: "MRO.L",  index_weight: 0.0045 },
  { symbol: "VOD.L",  name: "Vodafone Group plc",            country: "United Kingdom", sector: "Communication Services", stooq_ticker: "vod.uk",  finnhub_ticker: "VOD.L",  index_weight: 0.0040 },
  { symbol: "SGRO.L", name: "Segro plc",                     country: "United Kingdom", sector: "Real Estate",            stooq_ticker: "sgro.uk", finnhub_ticker: "SGRO.L", index_weight: 0.0040 },
  { symbol: "BATS.L", name: "British American Tobacco plc",  country: "United Kingdom", sector: "Consumer Staples",       stooq_ticker: "bats.uk", finnhub_ticker: "BATS.L", index_weight: 0.0080 },
  { symbol: "LSEG.L", name: "London Stock Exchange Group plc", country: "United Kingdom", sector: "Financials",           stooq_ticker: "lseg.uk", finnhub_ticker: "LSEG.L", index_weight: 0.0075 },
  { symbol: "TSCO.L", name: "Tesco plc",                     country: "United Kingdom", sector: "Consumer Staples",       stooq_ticker: "tsco.uk", finnhub_ticker: "TSCO.L", index_weight: 0.0050 },
  { symbol: "SSE.L",  name: "SSE plc",                       country: "United Kingdom", sector: "Utilities",              stooq_ticker: "sse.uk",  finnhub_ticker: "SSE.L",  index_weight: 0.0045 },
  { symbol: "AV.L",   name: "Aviva plc",                     country: "United Kingdom", sector: "Financials",             stooq_ticker: "av.uk",   finnhub_ticker: "AV.L",   index_weight: 0.0042 },
  { symbol: "LGEN.L", name: "Legal & General Group plc",     country: "United Kingdom", sector: "Financials",             stooq_ticker: "lgen.uk", finnhub_ticker: "LGEN.L", index_weight: 0.0040 },
  { symbol: "ANTO.L", name: "Antofagasta plc",               country: "United Kingdom", sector: "Materials",              stooq_ticker: "anto.uk", finnhub_ticker: "ANTO.L", index_weight: 0.0035 },
  { symbol: "IMB.L",  name: "Imperial Brands plc",           country: "United Kingdom", sector: "Consumer Staples",       stooq_ticker: "imb.uk",  finnhub_ticker: "IMB.L",  index_weight: 0.0035 },
  { symbol: "NXT.L",  name: "Next plc",                      country: "United Kingdom", sector: "Consumer Discretionary", stooq_ticker: "nxt.uk",  finnhub_ticker: "NXT.L",  index_weight: 0.0030 },
  { symbol: "ABF.L",  name: "Associated British Foods plc",  country: "United Kingdom", sector: "Consumer Staples",       stooq_ticker: "abf.uk",  finnhub_ticker: "ABF.L",  index_weight: 0.0028 },
  { symbol: "SN.L",    name: "Smith & Nephew plc",            country: "United Kingdom", sector: "Health Care",            stooq_ticker: "sn.uk",    finnhub_ticker: "SN.L",    index_weight: 0.0025 },
  { symbol: "BT-A.L", name: "BT Group plc",                  country: "United Kingdom", sector: "Communication Services", stooq_ticker: "bt-a.uk",  finnhub_ticker: "BT-A.L",  index_weight: 0.0018 },
  { symbol: "HLMA.L", name: "Halma plc",                      country: "United Kingdom", sector: "Industrials",            stooq_ticker: "hlma.uk",  finnhub_ticker: "HLMA.L",  index_weight: 0.0014 },
  { symbol: "AAF.L",  name: "Airtel Africa plc",              country: "United Kingdom", sector: "Communication Services", stooq_ticker: "aaf.uk",   finnhub_ticker: "AAF.L",   index_weight: 0.0012 },
  { symbol: "RTO.L",  name: "Rentokil Initial plc",           country: "United Kingdom", sector: "Industrials",            stooq_ticker: "rto.uk",   finnhub_ticker: "RTO.L",   index_weight: 0.0010 },
  { symbol: "INF.L",  name: "Informa plc",                    country: "United Kingdom", sector: "Industrials",            stooq_ticker: "inf.uk",   finnhub_ticker: "INF.L",   index_weight: 0.0009 },
  { symbol: "SVT.L",  name: "Severn Trent plc",               country: "United Kingdom", sector: "Utilities",              stooq_ticker: "svt.uk",   finnhub_ticker: "SVT.L",   index_weight: 0.0009 },
  { symbol: "UU.L",   name: "United Utilities Group plc",     country: "United Kingdom", sector: "Utilities",              stooq_ticker: "uu.uk",    finnhub_ticker: "UU.L",    index_weight: 0.0008 },
  { symbol: "SDR.L",  name: "Schroders plc",                  country: "United Kingdom", sector: "Financials",             stooq_ticker: "sdr.uk",   finnhub_ticker: "SDR.L",   index_weight: 0.0008 },
  { symbol: "ADM.L",  name: "Admiral Group plc",              country: "United Kingdom", sector: "Financials",             stooq_ticker: "adm.uk",   finnhub_ticker: "ADM.L",   index_weight: 0.0008 },
  { symbol: "CNA.L",  name: "Centrica plc",                   country: "United Kingdom", sector: "Utilities",              stooq_ticker: "cna.uk",   finnhub_ticker: "CNA.L",   index_weight: 0.0008 },
  { symbol: "WISE.L", name: "Wise plc",                       country: "United Kingdom", sector: "Financials",             stooq_ticker: "wise.uk",  finnhub_ticker: "WISE.L",  index_weight: 0.0008 },
  { symbol: "SMIN.L", name: "Smiths Group plc",               country: "United Kingdom", sector: "Industrials",            stooq_ticker: "smin.uk",  finnhub_ticker: "SMIN.L",  index_weight: 0.0008 },
  { symbol: "WEIR.L", name: "Weir Group plc",                 country: "United Kingdom", sector: "Industrials",            stooq_ticker: "weir.uk",  finnhub_ticker: "WEIR.L",  index_weight: 0.0007 },
  { symbol: "SBRY.L", name: "J Sainsbury plc",                country: "United Kingdom", sector: "Consumer Staples",       stooq_ticker: "sbry.uk",  finnhub_ticker: "SBRY.L",  index_weight: 0.0007 },
  { symbol: "SGE.L",  name: "Sage Group plc",                 country: "United Kingdom", sector: "Information Technology", stooq_ticker: "sge.uk",   finnhub_ticker: "SGE.L",   index_weight: 0.0007 },
  { symbol: "PHNX.L", name: "Phoenix Group Holdings plc",     country: "United Kingdom", sector: "Financials",             stooq_ticker: "phnx.uk",  finnhub_ticker: "PHNX.L",  index_weight: 0.0007 },
  { symbol: "MKS.L",  name: "Marks and Spencer Group plc",    country: "United Kingdom", sector: "Consumer Discretionary", stooq_ticker: "mks.uk",   finnhub_ticker: "MKS.L",   index_weight: 0.0007 },
  { symbol: "BEZ.L",  name: "Beazley plc",                    country: "United Kingdom", sector: "Financials",             stooq_ticker: "bez.uk",   finnhub_ticker: "BEZ.L",   index_weight: 0.0007 },
  { symbol: "MNG.L",  name: "M&G plc",                        country: "United Kingdom", sector: "Financials",             stooq_ticker: "mng.uk",   finnhub_ticker: "MNG.L",   index_weight: 0.0007 },
  { symbol: "DPLM.L", name: "Diploma plc",                    country: "United Kingdom", sector: "Industrials",            stooq_ticker: "dplm.uk",  finnhub_ticker: "DPLM.L",  index_weight: 0.0007 },
  { symbol: "BNZL.L", name: "Bunzl plc",                      country: "United Kingdom", sector: "Industrials",            stooq_ticker: "bnzl.uk",  finnhub_ticker: "BNZL.L",  index_weight: 0.0006 },
  { symbol: "BAB.L",  name: "Babcock International Group plc", country: "United Kingdom", sector: "Industrials",           stooq_ticker: "bab.uk",   finnhub_ticker: "BAB.L",   index_weight: 0.0006 },
  { symbol: "IMI.L",  name: "IMI plc",                        country: "United Kingdom", sector: "Industrials",            stooq_ticker: "imi.uk",   finnhub_ticker: "IMI.L",   index_weight: 0.0006 },
  { symbol: "STJ.L",  name: "St. James's Place plc",          country: "United Kingdom", sector: "Financials",             stooq_ticker: "stj.uk",   finnhub_ticker: "STJ.L",   index_weight: 0.0006 },
  { symbol: "ITRK.L", name: "Intertek Group plc",             country: "United Kingdom", sector: "Industrials",            stooq_ticker: "itrk.uk",  finnhub_ticker: "ITRK.L",  index_weight: 0.0006 },
  { symbol: "KGF.L",  name: "Kingfisher plc",                 country: "United Kingdom", sector: "Consumer Discretionary", stooq_ticker: "kgf.uk",   finnhub_ticker: "KGF.L",   index_weight: 0.0005 },
  { symbol: "GAW.L",  name: "Games Workshop Group plc",       country: "United Kingdom", sector: "Consumer Discretionary", stooq_ticker: "gaw.uk",   finnhub_ticker: "GAW.L",   index_weight: 0.0005 },
  { symbol: "SPX.L",  name: "Spirax-Sarco Engineering plc",   country: "United Kingdom", sector: "Industrials",            stooq_ticker: "spx.uk",   finnhub_ticker: "SPX.L",   index_weight: 0.0005 },

  // ── SPAIN (21) ──────────────────────────────────────────────────────────────
  { symbol: "SAN.MC",  name: "Banco Santander SA",                    country: "Spain", sector: "Financials",             stooq_ticker: "san.es",  finnhub_ticker: "SAN.MC",  index_weight: 0.0222 },
  { symbol: "IBE.MC",  name: "Iberdrola SA",                          country: "Spain", sector: "Utilities",              stooq_ticker: "ibe.es",  finnhub_ticker: "IBE.MC",  index_weight: 0.0180 },
  { symbol: "ITX.MC",  name: "Inditex SA",                            country: "Spain", sector: "Consumer Discretionary", stooq_ticker: "itx.es",  finnhub_ticker: "ITX.MC",  index_weight: 0.0160 },
  { symbol: "BBVA.MC", name: "Banco Bilbao Vizcaya Argentaria SA",    country: "Spain", sector: "Financials",             stooq_ticker: "bbva.es", finnhub_ticker: "BBVA.MC", index_weight: 0.0150 },
  { symbol: "AMS.MC",  name: "Amadeus IT Group SA",                   country: "Spain", sector: "Information Technology", stooq_ticker: "ams.es",  finnhub_ticker: "AMS.MC",  index_weight: 0.0055 },
  { symbol: "CLNX.MC", name: "Cellnex Telecom SA",                    country: "Spain", sector: "Communication Services", stooq_ticker: "clnx.es", finnhub_ticker: "CLNX.MC", index_weight: 0.0050 },
  { symbol: "REP.MC",  name: "Repsol SA",                             country: "Spain", sector: "Energy",                 stooq_ticker: "rep.es",  finnhub_ticker: "REP.MC",  index_weight: 0.0045 },
  { symbol: "TEF.MC",  name: "Telefónica SA",                         country: "Spain", sector: "Communication Services", stooq_ticker: "tef.es",  finnhub_ticker: "TEF.MC",  index_weight: 0.0040 },
  { symbol: "CABK.MC", name: "CaixaBank SA",                          country: "Spain", sector: "Financials",             stooq_ticker: "cabk.es", finnhub_ticker: "CABK.MC", index_weight: 0.0045 },
  { symbol: "FER.MC",  name: "Ferrovial SE",                          country: "Spain", sector: "Industrials",            stooq_ticker: "fer.es",  finnhub_ticker: "FER.MC",  index_weight: 0.0040 },
  { symbol: "AENA.MC", name: "Aena SME SA",                           country: "Spain", sector: "Industrials",            stooq_ticker: "aena.es", finnhub_ticker: "AENA.MC", index_weight: 0.0035 },
  { symbol: "ELE.MC",  name: "Endesa SA",                             country: "Spain", sector: "Utilities",              stooq_ticker: "ele.es",  finnhub_ticker: "ELE.MC",  index_weight: 0.0030 },
  { symbol: "ACS.MC",  name: "Grupo ACS SA",                          country: "Spain", sector: "Industrials",            stooq_ticker: "acs.es",  finnhub_ticker: "ACS.MC",  index_weight: 0.0025 },
  { symbol: "IAG.MC",  name: "International Consolidated Airlines Group SA", country: "Spain", sector: "Industrials",    stooq_ticker: "iag.es",  finnhub_ticker: "IAG.MC",  index_weight: 0.0021 },
  { symbol: "NTGY.MC", name: "Naturgy Energy Group SA",               country: "Spain", sector: "Utilities",              stooq_ticker: "ntgy.es", finnhub_ticker: "NTGY.MC", index_weight: 0.0020 },
  { symbol: "SAB.MC",  name: "Banco Sabadell SA",                     country: "Spain", sector: "Financials",             stooq_ticker: "sab.es",  finnhub_ticker: "SAB.MC",  index_weight: 0.0013 },
  { symbol: "PUIG.MC", name: "Puig Brands SA",                        country: "Spain", sector: "Consumer Staples",       stooq_ticker: "puig.es", finnhub_ticker: "PUIG.MC", index_weight: 0.0013 },
  { symbol: "BKT.MC",  name: "Bankinter SA",                          country: "Spain", sector: "Financials",             stooq_ticker: "bkt.es",  finnhub_ticker: "BKT.MC",  index_weight: 0.0011 },
  { symbol: "ANA.MC",  name: "Acciona SA",                            country: "Spain", sector: "Industrials",            stooq_ticker: "ana.es",  finnhub_ticker: "ANA.MC",  index_weight: 0.0011 },
  { symbol: "MAP.MC",  name: "Mapfre SA",                             country: "Spain", sector: "Financials",             stooq_ticker: "map.es",  finnhub_ticker: "MAP.MC",  index_weight: 0.0010 },
  { symbol: "IDR.MC",  name: "Indra Sistemas SA",                     country: "Spain", sector: "Information Technology", stooq_ticker: "idr.es",  finnhub_ticker: "IDR.MC",  index_weight: 0.0010 },

  // ── ITALY (22) ──────────────────────────────────────────────────────────────
  { symbol: "UCG.MI",   name: "UniCredit SpA",      country: "Italy", sector: "Financials",             stooq_ticker: "ucg.it",   finnhub_ticker: "UCG.MI",   index_weight: 0.0090 },
  { symbol: "RACE.MI",  name: "Ferrari NV",         country: "Italy", sector: "Consumer Discretionary", stooq_ticker: "race.it",  finnhub_ticker: "RACE.MI",  index_weight: 0.0080 },
  { symbol: "ENEL.MI",  name: "Enel SpA",           country: "Italy", sector: "Utilities",              stooq_ticker: "enel.it",  finnhub_ticker: "ENEL.MI",  index_weight: 0.0080 },
  { symbol: "ISP.MI",   name: "Intesa Sanpaolo SpA", country: "Italy", sector: "Financials",            stooq_ticker: "isp.it",   finnhub_ticker: "ISP.MI",   index_weight: 0.0070 },
  { symbol: "STLAM.MI", name: "Stellantis NV",      country: "Italy", sector: "Consumer Discretionary", stooq_ticker: "stlam.it", finnhub_ticker: "STLAM.MI", index_weight: 0.0070 },
  { symbol: "ENI.MI",   name: "ENI SpA",            country: "Italy", sector: "Energy",                 stooq_ticker: "eni.it",   finnhub_ticker: "ENI.MI",   index_weight: 0.0065 },
  { symbol: "PRY.MI",   name: "Prysmian SpA",       country: "Italy", sector: "Industrials",            stooq_ticker: "pry.it",   finnhub_ticker: "PRY.MI",   index_weight: 0.0045 },
  { symbol: "G.MI",    name: "Assicurazioni Generali SpA", country: "Italy", sector: "Financials",         stooq_ticker: "g.it",     finnhub_ticker: "G.MI",     index_weight: 0.0060 },
  { symbol: "LDO.MI",  name: "Leonardo SpA",                  country: "Italy", sector: "Industrials",            stooq_ticker: "ldo.it",   finnhub_ticker: "LDO.MI",   index_weight: 0.0040 },
  { symbol: "PST.MI",  name: "Poste Italiane SpA",            country: "Italy", sector: "Industrials",            stooq_ticker: "pst.it",   finnhub_ticker: "PST.MI",   index_weight: 0.0025 },
  { symbol: "BMPS.MI", name: "Banca Monte dei Paschi di Siena SpA", country: "Italy", sector: "Financials",       stooq_ticker: "bmps.it",  finnhub_ticker: "BMPS.MI",  index_weight: 0.0020 },
  { symbol: "BPE.MI",  name: "BPER Banca SpA",                country: "Italy", sector: "Financials",            stooq_ticker: "bpe.it",   finnhub_ticker: "BPE.MI",   index_weight: 0.0020 },
  { symbol: "SRG.MI",  name: "Snam SpA",                      country: "Italy", sector: "Utilities",             stooq_ticker: "srg.it",   finnhub_ticker: "SRG.MI",   index_weight: 0.0019 },
  { symbol: "TRN.MI",  name: "Terna SpA",                     country: "Italy", sector: "Utilities",             stooq_ticker: "trn.it",   finnhub_ticker: "TRN.MI",   index_weight: 0.0017 },
  { symbol: "BAMI.MI", name: "Banco BPM SpA",                 country: "Italy", sector: "Financials",            stooq_ticker: "bami.it",  finnhub_ticker: "BAMI.MI",  index_weight: 0.0016 },
  { symbol: "MONC.MI", name: "Moncler SpA",                   country: "Italy", sector: "Consumer Discretionary", stooq_ticker: "monc.it",  finnhub_ticker: "MONC.MI",  index_weight: 0.0013 },
  { symbol: "UNI.MI",  name: "Unipol Assicurazioni SpA",      country: "Italy", sector: "Financials",            stooq_ticker: "uni.it",   finnhub_ticker: "UNI.MI",   index_weight: 0.0012 },
  { symbol: "MB.MI",   name: "Mediobanca SpA",                country: "Italy", sector: "Financials",            stooq_ticker: "mb.it",    finnhub_ticker: "MB.MI",    index_weight: 0.0012 },
  { symbol: "TIT.MI",  name: "Telecom Italia SpA",            country: "Italy", sector: "Communication Services", stooq_ticker: "tit.it",  finnhub_ticker: "TIT.MI",   index_weight: 0.0012 },
  { symbol: "BMED.MI", name: "Banca Mediolanum SpA",          country: "Italy", sector: "Financials",            stooq_ticker: "bmed.it",  finnhub_ticker: "BMED.MI",  index_weight: 0.0012 },
  { symbol: "FBK.MI",  name: "FinecoBank SpA",                country: "Italy", sector: "Financials",            stooq_ticker: "fbk.it",   finnhub_ticker: "FBK.MI",   index_weight: 0.0011 },
  { symbol: "IG.MI",   name: "Italgas SpA",                   country: "Italy", sector: "Utilities",             stooq_ticker: "ig.it",    finnhub_ticker: "IG.MI",    index_weight: 0.0010 },

  // ── SWITZERLAND (10) ────────────────────────────────────────────────────────
  { symbol: "NESN.SW",  name: "Nestlé SA",                         country: "Switzerland", sector: "Consumer Staples",       stooq_ticker: "nesn.ch",  finnhub_ticker: "NESN.SW",  index_weight: 0.0180 },
  { symbol: "ROG.SW",   name: "Roche Holding AG",                  country: "Switzerland", sector: "Health Care",            stooq_ticker: "rog.ch",   finnhub_ticker: "ROG.SW",   index_weight: 0.0160 },
  { symbol: "NOVN.SW",  name: "Novartis AG",                       country: "Switzerland", sector: "Health Care",            stooq_ticker: "novn.ch",  finnhub_ticker: "NOVN.SW",  index_weight: 0.0170 },
  { symbol: "ABBN.SW",  name: "ABB Ltd",                           country: "Switzerland", sector: "Industrials",            stooq_ticker: "abbn.ch",  finnhub_ticker: "ABBN.SW",  index_weight: 0.0080 },
  { symbol: "UBSG.SW",  name: "UBS Group AG",                      country: "Switzerland", sector: "Financials",             stooq_ticker: "ubsg.ch",  finnhub_ticker: "UBSG.SW",  index_weight: 0.0090 },
  { symbol: "CFR.SW",   name: "Compagnie Financière Richemont SA", country: "Switzerland", sector: "Consumer Discretionary", stooq_ticker: "cfr.ch",   finnhub_ticker: "CFR.SW",   index_weight: 0.0120 },
  { symbol: "ZURN.SW",  name: "Zurich Insurance Group AG",         country: "Switzerland", sector: "Financials",             stooq_ticker: "zurn.ch",  finnhub_ticker: "ZURN.SW",  index_weight: 0.0065 },
  { symbol: "SREN.SW",  name: "Swiss Re AG",                       country: "Switzerland", sector: "Financials",             stooq_ticker: "sren.ch",  finnhub_ticker: "SREN.SW",  index_weight: 0.0055 },
  { symbol: "HOLN.SW",  name: "Holcim Ltd",                        country: "Switzerland", sector: "Materials",              stooq_ticker: "holn.ch",  finnhub_ticker: "HOLN.SW",  index_weight: 0.0055 },
  { symbol: "SCMN.SW",  name: "Swisscom AG",                       country: "Switzerland", sector: "Communication Services", stooq_ticker: "scmn.ch",  finnhub_ticker: "SCMN.SW",  index_weight: 0.0040 },

  // ── DENMARK (10) ────────────────────────────────────────────────────────────
  { symbol: "NOVO-B.CO",   name: "Novo Nordisk A/S",              country: "Denmark", sector: "Health Care",  stooq_ticker: "novob.dk",   finnhub_ticker: "NOVO-B.CO",   index_weight: 0.0250 },
  { symbol: "MAERSK-B.CO", name: "A.P. Møller-Maersk A/S",        country: "Denmark", sector: "Industrials",  stooq_ticker: "maerskb.dk", finnhub_ticker: "MAERSK-B.CO", index_weight: 0.0040 },
  { symbol: "DSV.CO",      name: "DSV A/S",                        country: "Denmark", sector: "Industrials",  stooq_ticker: "dsv.dk",     finnhub_ticker: "DSV.CO",      index_weight: 0.0050 },
  { symbol: "DANSKE.CO",   name: "Danske Bank A/S",                country: "Denmark", sector: "Financials",   stooq_ticker: "danske.dk",  finnhub_ticker: "DANSKE.CO",   index_weight: 0.0030 },
  { symbol: "ORSTED.CO",  name: "Ørsted A/S",                     country: "Denmark", sector: "Utilities",    stooq_ticker: "orsted.dk",  finnhub_ticker: "ORSTED.CO",   index_weight: 0.0022 },
  { symbol: "NSIS-B.CO",  name: "Novonesis A/S",                  country: "Denmark", sector: "Materials",    stooq_ticker: "nsisb.dk",   finnhub_ticker: "NSIS-B.CO",   index_weight: 0.0020 }, // VERIFY: formerly Novozymes NZYM-B.CO; rebranded 2024
  { symbol: "VWS.CO",     name: "Vestas Wind Systems A/S",        country: "Denmark", sector: "Industrials",  stooq_ticker: "vws.dk",     finnhub_ticker: "VWS.CO",      index_weight: 0.0019 },
  { symbol: "CARL-B.CO",  name: "Carlsberg A/S",                  country: "Denmark", sector: "Consumer Staples", stooq_ticker: "carlb.dk", finnhub_ticker: "CARL-B.CO",  index_weight: 0.0015 },
  { symbol: "COLO-B.CO",  name: "Coloplast A/S",                  country: "Denmark", sector: "Health Care",      stooq_ticker: "colob.dk",  finnhub_ticker: "COLO-B.CO",  index_weight: 0.0012 },
  { symbol: "TRYG.CO",    name: "Tryg A/S",                       country: "Denmark", sector: "Financials",       stooq_ticker: "tryg.dk",   finnhub_ticker: "TRYG.CO",    index_weight: 0.0011 },

  // ── FINLAND (9) ─────────────────────────────────────────────────────────────
  { symbol: "KNEBV.HE", name: "KONE Oyj",   country: "Finland", sector: "Industrials",            stooq_ticker: "knebv.fi", finnhub_ticker: "KNEBV.HE", index_weight: 0.0050 },
  { symbol: "SAMPO.HE", name: "Sampo Oyj",  country: "Finland", sector: "Financials",             stooq_ticker: "sampo.fi", finnhub_ticker: "SAMPO.HE", index_weight: 0.0045 },
  { symbol: "NESTE.HE", name: "Neste Oyj",  country: "Finland", sector: "Energy",                 stooq_ticker: "neste.fi", finnhub_ticker: "NESTE.HE", index_weight: 0.0040 },
  { symbol: "NOKIA.HE", name: "Nokia Oyj",      country: "Finland", sector: "Information Technology", stooq_ticker: "nokia.fi", finnhub_ticker: "NOKIA.HE", index_weight: 0.0035 },
  { symbol: "NDA-FI.HE",  name: "Nordea Bank Abp",    country: "Finland", sector: "Financials",            stooq_ticker: "ndafi.fi",   finnhub_ticker: "NDA-FI.HE",  index_weight: 0.0055 },
  { symbol: "WRT1V.HE",   name: "Wärtsilä Oyj",       country: "Finland", sector: "Industrials",           stooq_ticker: "wrt1v.fi",   finnhub_ticker: "WRT1V.HE",   index_weight: 0.0018 },
  { symbol: "FORTUM.HE",  name: "Fortum Oyj",          country: "Finland", sector: "Utilities",             stooq_ticker: "fortum.fi",  finnhub_ticker: "FORTUM.HE",  index_weight: 0.0016 },
  { symbol: "UPM.HE",     name: "UPM-Kymmene Oyj",     country: "Finland", sector: "Materials",             stooq_ticker: "upm.fi",     finnhub_ticker: "UPM.HE",     index_weight: 0.0012 },
  { symbol: "METSO.HE",   name: "Metso Oyj",           country: "Finland", sector: "Industrials",           stooq_ticker: "metso.fi",   finnhub_ticker: "METSO.HE",   index_weight: 0.0012 },

  // ── SWEDEN (25) ─────────────────────────────────────────────────────────────
  { symbol: "INVE-B.ST",  name: "Investor AB",                    country: "Sweden", sector: "Financials",             stooq_ticker: "inveb.se",  finnhub_ticker: "INVE-B.ST",  index_weight: 0.0080 },
  { symbol: "ATCO-B.ST",  name: "Atlas Copco AB",                 country: "Sweden", sector: "Industrials",            stooq_ticker: "atcob.se",  finnhub_ticker: "ATCO-B.ST",  index_weight: 0.0080 },
  { symbol: "VOLV-A.ST",  name: "Volvo AB",                       country: "Sweden", sector: "Industrials",            stooq_ticker: "volva.se",  finnhub_ticker: "VOLV-A.ST",  index_weight: 0.0060 },
  { symbol: "SAND.ST",    name: "Sandvik AB",                     country: "Sweden", sector: "Industrials",            stooq_ticker: "sand.se",   finnhub_ticker: "SAND.ST",    index_weight: 0.0035 },
  { symbol: "ASSA-B.ST",  name: "Assa Abloy AB",                  country: "Sweden", sector: "Industrials",            stooq_ticker: "assab.se",  finnhub_ticker: "ASSA-B.ST",  index_weight: 0.0030 },
  { symbol: "SEB-A.ST",   name: "Skandinaviska Enskilda Banken",  country: "Sweden", sector: "Financials",             stooq_ticker: "seba.se",   finnhub_ticker: "SEB-A.ST",   index_weight: 0.0040 },
  { symbol: "SWED-A.ST",  name: "Swedbank AB",                    country: "Sweden", sector: "Financials",             stooq_ticker: "sweda.se",  finnhub_ticker: "SWED-A.ST",  index_weight: 0.0030 },
  { symbol: "SAAB-B.ST",   name: "Saab AB",                       country: "Sweden", sector: "Industrials",            stooq_ticker: "saabb.se",   finnhub_ticker: "SAAB-B.ST",   index_weight: 0.0030 },
  { symbol: "EQT.ST",      name: "EQT AB",                        country: "Sweden", sector: "Financials",             stooq_ticker: "eqt.se",     finnhub_ticker: "EQT.ST",      index_weight: 0.0028 },
  { symbol: "EPI-A.ST",    name: "Epiroc AB",                     country: "Sweden", sector: "Industrials",            stooq_ticker: "epia.se",    finnhub_ticker: "EPI-A.ST",    index_weight: 0.0025 },
  { symbol: "HM-B.ST",     name: "H & M Hennes & Mauritz AB",    country: "Sweden", sector: "Consumer Discretionary", stooq_ticker: "hmb.se",     finnhub_ticker: "HM-B.ST",     index_weight: 0.0024 },
  { symbol: "HEXA-B.ST",   name: "Hexagon AB",                    country: "Sweden", sector: "Information Technology", stooq_ticker: "hexab.se",   finnhub_ticker: "HEXA-B.ST",   index_weight: 0.0022 },
  { symbol: "SHB-A.ST",    name: "Svenska Handelsbanken AB",      country: "Sweden", sector: "Financials",             stooq_ticker: "shba.se",    finnhub_ticker: "SHB-A.ST",    index_weight: 0.0023 },
  { symbol: "ALFA.ST",     name: "Alfa Laval AB",                 country: "Sweden", sector: "Industrials",            stooq_ticker: "alfa.se",    finnhub_ticker: "ALFA.ST",     index_weight: 0.0018 },
  { symbol: "INDU-A.ST",   name: "Industrivärden AB",             country: "Sweden", sector: "Financials",             stooq_ticker: "indua.se",   finnhub_ticker: "INDU-A.ST",   index_weight: 0.0018 },
  { symbol: "BOL.ST",      name: "Boliden AB",                    country: "Sweden", sector: "Materials",              stooq_ticker: "bol.se",     finnhub_ticker: "BOL.ST",      index_weight: 0.0016 },
  { symbol: "ESSITY-B.ST", name: "Essity AB",                     country: "Sweden", sector: "Consumer Staples",       stooq_ticker: "essityb.se", finnhub_ticker: "ESSITY-B.ST", index_weight: 0.0015 },
  { symbol: "TELIA.ST",    name: "Telia Company AB",               country: "Sweden", sector: "Communication Services", stooq_ticker: "telia.se",    finnhub_ticker: "TELIA.ST",    index_weight: 0.0015 },
  { symbol: "LUND-B.ST",  name: "Lundbergföretagen AB",           country: "Sweden", sector: "Financials",             stooq_ticker: "lundb.se",    finnhub_ticker: "LUND-B.ST",   index_weight: 0.0012 },
  { symbol: "LIFCO-B.ST", name: "Lifco AB",                       country: "Sweden", sector: "Industrials",            stooq_ticker: "lifcob.se",   finnhub_ticker: "LIFCO-B.ST",  index_weight: 0.0012 },
  { symbol: "LATO-B.ST",  name: "Investment AB Latour",           country: "Sweden", sector: "Financials",             stooq_ticker: "latob.se",    finnhub_ticker: "LATO-B.ST",   index_weight: 0.0012 },
  { symbol: "SOBI.ST",    name: "Swedish Orphan Biovitrum AB",    country: "Sweden", sector: "Health Care",            stooq_ticker: "sobi.se",     finnhub_ticker: "SOBI.ST",     index_weight: 0.0011 },
  { symbol: "TEL2-B.ST",  name: "Tele2 AB",                       country: "Sweden", sector: "Communication Services", stooq_ticker: "tel2b.se",    finnhub_ticker: "TEL2-B.ST",   index_weight: 0.0011 },
  { symbol: "SKA-B.ST",   name: "Skanska AB",                     country: "Sweden", sector: "Industrials",            stooq_ticker: "skab.se",     finnhub_ticker: "SKA-B.ST",    index_weight: 0.0009 },
  { symbol: "SKF-B.ST",   name: "SKF AB",                         country: "Sweden", sector: "Industrials",            stooq_ticker: "skfb.se",     finnhub_ticker: "SKF-B.ST",    index_weight: 0.0009 },

  // ── BELGIUM (6) ─────────────────────────────────────────────────────────────
  { symbol: "ABI.BR",  name: "Anheuser-Busch InBev SA/NV", country: "Belgium", sector: "Consumer Staples", stooq_ticker: "abi.be",  finnhub_ticker: "ABI.BR",  index_weight: 0.0120 },
  { symbol: "KBC.BR",  name: "KBC Group NV",               country: "Belgium", sector: "Financials",       stooq_ticker: "kbc.be",  finnhub_ticker: "KBC.BR",  index_weight: 0.0040 },
  { symbol: "UCB.BR",  name: "UCB SA",                     country: "Belgium", sector: "Health Care",      stooq_ticker: "ucb.be",  finnhub_ticker: "UCB.BR",  index_weight: 0.0035 },
  { symbol: "ARGX.BR", name: "Argenx SE",                  country: "Belgium", sector: "Health Care",      stooq_ticker: "argx.be", finnhub_ticker: "ARGX.BR", index_weight: 0.0045 },
  { symbol: "ELI.BR",  name: "Elia Group SA/NV",           country: "Belgium", sector: "Utilities",        stooq_ticker: "eli.be",  finnhub_ticker: "ELI.BR",  index_weight: 0.0013 },
  { symbol: "AGS.BR",  name: "ageas SA/NV",                country: "Belgium", sector: "Financials",       stooq_ticker: "ags.be",  finnhub_ticker: "AGS.BR",  index_weight: 0.0010 },

  // ── AUSTRIA (5) ─────────────────────────────────────────────────────────────
  { symbol: "EBS.VI",  name: "Erste Group Bank AG",         country: "Austria", sector: "Financials",       stooq_ticker: "ebs.at",  finnhub_ticker: "EBS.VI",  index_weight: 0.0035 },
  { symbol: "VER.VI",  name: "Verbund AG",                  country: "Austria", sector: "Utilities",        stooq_ticker: "ver.at",  finnhub_ticker: "VER.VI",  index_weight: 0.0019 },
  { symbol: "OMV.VI",  name: "OMV AG",                      country: "Austria", sector: "Energy",           stooq_ticker: "omv.at",  finnhub_ticker: "OMV.VI",  index_weight: 0.0016 },
  { symbol: "RBI.VI",  name: "Raiffeisen Bank International AG", country: "Austria", sector: "Financials",   stooq_ticker: "rbi.at",  finnhub_ticker: "RBI.VI",  index_weight: 0.0012 },
  { symbol: "0B2.F",   name: "BAWAG Group AG",               country: "Austria", sector: "Financials",       stooq_ticker: "bwb.at",  finnhub_ticker: "0B2.F",   index_weight: 0.0009 },

  // ── IRELAND (5) ─────────────────────────────────────────────────────────────
  { symbol: "RYA.IR",  name: "Ryanair Holdings plc",        country: "Ireland", sector: "Industrials",      stooq_ticker: "rya.ie",  finnhub_ticker: "RYA.IR",  index_weight: 0.0026 },
  { symbol: "A5G.IR",  name: "AIB Group plc",               country: "Ireland", sector: "Financials",       stooq_ticker: "a5g.ie",  finnhub_ticker: "A5G.IR",  index_weight: 0.0017 },
  { symbol: "BIRG.IR", name: "Bank of Ireland Group plc",   country: "Ireland", sector: "Financials",       stooq_ticker: "birg.ie", finnhub_ticker: "BIRG.IR", index_weight: 0.0013 },
  { symbol: "KRX.IR",  name: "Kingspan Group plc",          country: "Ireland", sector: "Industrials",      stooq_ticker: "krx.ie",  finnhub_ticker: "KRX.IR",  index_weight: 0.0013 },
  { symbol: "KRZ.IR",  name: "Kerry Group plc",             country: "Ireland", sector: "Consumer Staples", stooq_ticker: "krz.ie",  finnhub_ticker: "KRZ.IR",  index_weight: 0.0010 },
];

// Total: 23 NL + 46 DE + 47 FR + 70 UK + 21 ES + 22 IT + 10 CH + 10 DK + 9 FI + 25 SE + 6 BE + 5 AT + 5 IE = 299 companies
